spaceone-dev/identity

src/spaceone/identity/info/common_info.py
test/api/test_domain.py

Add total_count to StatisticsQuery result

---

src/spaceone/identity/conf/provider_conf.py

Change google provider's supported schema

---

src/spaceone/identity/lib/key_generator.py

Add user_type to api key playload

---

src/spaceone/identity/connector/secret_connector.py
src/spaceone/identity/manager/service_account_manager.py
src/spaceone/identity/service/service_account_service.py

Secret: Deny -> Cascade Delete

Change ServiceAccount delete policy

---

src/spaceone/identity/conf/global_conf.py

Change Token Policy

---

src/spaceone/identity/conf/provider_conf.py

Signed-off-by: Choonho Son <choonhoson@megazone.com>

Update icon URL

---

src/spaceone/identity/model/provider_model.py

Change default provider sorting

---

src/spaceone/identity/conf/provider_conf.py

Change aws provider help

---

src/spaceone/identity/conf/provider_conf.py

Change a google cloud provider's schema

---

src/spaceone/identity/conf/provider_conf.py

Change required fields

---

test/api/test_api_key.py

Change test case file

---

src/spaceone/identity/conf/provider_conf.py

Change a provider's link template format (jinja2 -> ejs)

---

src/spaceone/identity/conf/provider_conf.py

Add a console link template in google_cloud provider

---

src/spaceone/identity/conf/provider_conf.py

Change provider help

---

src/spaceone/identity/conf/provider_conf.py

Change default provider config

---

src/spaceone/identity/model/project_model.py

Change default aggregate lookup key

---

Dockerfile
pkg/pip_requirements.txt

Change a Dockerfile

---

src/setup.py
src/spaceone/identity/model/project_model.py
src/spaceone/identity/model/service_account_model.py

Change aggregate lookup field

---

src/spaceone/identity/model/project_model.py
src/spaceone/identity/model/service_account_model.py

remove aggregate lookup conf in model

---

src/spaceone/identity/connector/auth_plugin_connector.py
src/spaceone/identity/manager/domain_manager.py
src/spaceone/identity/model/domain_model.py

Signed-off-by: “Choonho <choonhoson@megazone.com>

Support Auth.init

---

src/spaceone/identity/manager/domain_manager.py

Signed-off-by: “Choonho <choonhoson@megazone.com>

Fix Auth.init

---

src/spaceone/identity/conf/global_conf.py

Change token timeout value

---

src/spaceone/identity/model/domain_model.py
src/spaceone/identity/model/policy_model.py
src/spaceone/identity/model/project_group_model.py
src/spaceone/identity/model/project_model.py
src/spaceone/identity/model/provider_model.py
src/spaceone/identity/model/role_model.py
src/spaceone/identity/model/service_account_model.py
src/spaceone/identity/model/user_model.py

Add compound index for tags

---

src/spaceone/identity/service/domain_service.py
src/spaceone/identity/service/policy_service.py
src/spaceone/identity/service/project_group_service.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/provider_service.py
src/spaceone/identity/service/role_service.py
src/spaceone/identity/service/service_account_service.py
src/spaceone/identity/service/user_service.py

Add tag search spec

---

src/spaceone/identity/info/find_user_info.py
src/spaceone/identity/manager/token_manager/external_token_manager.py

Bug fix: fix find user and issue token bugs

---

src/spaceone/identity/manager/token_manager/__init__.py

Change a refresh token key's length

---

src/spaceone/identity/service/authorization_service.py

Change auth settings

---

src/spaceone/identity/model/policy_model.py

Fix a duplicate managed policy id bug

---

src/spaceone/identity/conf/provider_conf.py

Change a azure provider's icon

---

src/spaceone/identity/model/policy_model.py

Change policy model's unique conditions

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/model/api_key_model.py
src/spaceone/identity/model/domain_model.py
src/spaceone/identity/model/domain_owner_model.py
src/spaceone/identity/model/domain_secret_model.py
src/spaceone/identity/model/policy_model.py
src/spaceone/identity/model/project_group_model.py
src/spaceone/identity/model/project_model.py
src/spaceone/identity/model/provider_model.py
src/spaceone/identity/model/role_binding_model.py
src/spaceone/identity/model/role_model.py
src/spaceone/identity/model/service_account_model.py
src/spaceone/identity/model/user_model.py

Apply db index and unique check features

---

src/spaceone/identity/conf/global_conf.py
src/spaceone/identity/info/project_group_info.py
src/spaceone/identity/info/project_info.py
src/spaceone/identity/info/role_binding_info.py
src/spaceone/identity/info/service_account_info.py
src/spaceone/identity/model/project_group_model.py
src/spaceone/identity/model/project_model.py
src/spaceone/identity/model/role_binding_model.py
src/spaceone/identity/model/service_account_model.py
src/spaceone/identity/service/project_group_service.py
src/spaceone/identity/service/project_service.py
src/spaceone/identity/service/role_binding_service.py
src/spaceone/identity/service/service_account_service.py
test/factory/project_factory.py
test/factory/project_group_factory.py
test/factory/service_account_factory.py
test/service/test_provider_service.py
test/service/test_service_account_service.py

Insert reference_id into model using reference field.

---

src/spaceone/identity/model/project_group_model.py
src/spaceone/identity/model/project_model.py
src/spaceone/identity/model/role_binding_model.py

Add reference query keys

---

src/spaceone/identity/service/project_group_service.py
src/spaceone/identity/service/service_account_service.py

Fix authorization bugs

---

src/spaceone/identity/connector/auth_plugin_connector.py

Fix a plugin call bug

---

src/spaceone/identity/service/authorization_service.py
src/spaceone/identity/service/endpoint_service.py
src/spaceone/identity/service/project_group_service.py

Change a ProjectGroup's authorization scope

---

src/spaceone/identity/service/project_group_service.py

Fix a project group cache bug

---

src/spaceone/identity/service/project_group_service.py

Change ProjectGroup.list api's authorization scope

---

src/spaceone/identity/service/project_group_service.py

Fix a domain role filter bug

---

src/spaceone/identity/manager/project_manager.py
src/spaceone/identity/service/authorization_service.py
src/spaceone/identity/service/project_group_service.py

Grant permission to list parent project groups when in project member

---

src/spaceone/identity/service/project_group_service.py

Fix a permission bug

---

test/api/test_api_key.py
test/api/test_authorization.py
test/api/test_domain.py
test/api/test_policy.py
test/api/test_project.py
test/api/test_project_group.py
test/api/test_role.py
test/api/test_role_binding.py
test/api/test_token.py
test/api/test_user.py

Change stat api's test cases

---

src/spaceone/identity/service/project_service.py

Change a identity.Project.list's authorization scope

---

src/spaceone/identity/service/project_group_service.py

Change project group filter's conditions

---

src/spaceone/identity/service/token_service.py

Add debug code

---

src/spaceone/identity/manager/token_manager/__init__.py

Add a refresh token test code

---

src/spaceone/identity/manager/policy_manager.py

Fix a tags format bug

---

src/spaceone/identity/api/v1/domain.py
src/spaceone/identity/error/error_domain.py
src/spaceone/identity/manager/domain_manager.py
src/spaceone/identity/service/domain_service.py

Signed-off-by: “Choonho <choonhoson@megazone.com>

update auth API

---

src/spaceone/identity/manager/policy_manager.py

Remove debug code

---

src/spaceone/identity/manager/domain_manager.py

Signed-off-by: “Choonho <choonhoson@megazone.com>

Fix change_auth_plugin

---

src/spaceone/identity/service/role_binding_service.py

Add name keyword search in identity.RoleBinding

---

src/spaceone/identity/manager/token_manager/external_token_manager.py
src/spaceone/identity/service/token_service.py

Implement external authentication without user_id

---

src/spaceone/identity/manager/token_manager/__init__.py

etc: add debug code

---

src/spaceone/identity/info/domain_info.py

feat: change domain's plugin_info

---

src/spaceone/identity/manager/domain_manager.py

fix: fix a argument bug

---

src/spaceone/identity/manager/domain_manager.py

fix: fix typo

---

src/spaceone/identity/manager/domain_manager.py

refactor: change plugin info update

---

src/spaceone/identity/manager/domain_manager.py

fix: fix bug

---

src/spaceone/identity/conf/global_conf.py

refactor: remove unused configuration

---

src/spaceone/identity/manager/role_binding_manager.py

fix: fix to not assign duplicate domain roles

---

src/spaceone/identity/conf/provider_conf.py

feat: remove oci and alibaba cloud from default provider

---

src/spaceone/identity/service/service_account_service.py

fix: fix a bug that occurred when creating a schemaless service account

---

src/spaceone/identity/conf/provider_conf.py

feat: change default provider config

---

src/spaceone/identity/manager/authorization_manager.py
src/spaceone/identity/model/api_key_model.py
src/spaceone/identity/service/api_key_service.py
src/spaceone/identity/service/authorization_service.py

refactor: add USER scope for authorization

---

src/spaceone/identity/manager/authorization_manager.py

fix: fix authorization bug

---

src/spaceone/identity/model/service_account_model.py

refactor: add index to service account model

---

src/spaceone/identity/manager/role_binding_manager.py

fix: fix role binding bug

---

src/spaceone/identity/manager/authorization_manager.py

fix: fix permission bug

---

src/spaceone/identity/manager/token_manager/external_token_manager.py

test: add debug code

---

src/spaceone/identity/manager/token_manager/external_token_manager.py

feat: add automatic user creation on first login

---

src/spaceone/identity/connector/auth_plugin_connector.py
src/spaceone/identity/manager/token_manager/external_token_manager.py

refactor: add secret_data when calling plugin's login api

---

src/spaceone/identity/manager/token_manager/external_token_manager.py

refactor: remove secret_data when calling plugin's login api

---

src/spaceone/identity/service/user_service.py

Default language

---

src/spaceone/identity/manager/token_manager/external_token_manager.py
src/spaceone/identity/manager/token_manager/local_token_manager.py

fix: fix an authentication bug for users with different backends

---

src/spaceone/identity/manager/token_manager/external_token_manager.py

fix: fix bug of auto_create_user

---

src/spaceone/identity/manager/token_manager/external_token_manager.py
src/spaceone/identity/manager/user_manager.py

fix: fix permission error in auto_create_user

---

src/spaceone/identity/manager/user_manager.py

fix: fix bug when adding member

---

src/spaceone/identity/manager/user_manager.py
src/spaceone/identity/model/user_model.py

fix: remove spaces from name and email when creating a user

---

src/spaceone/identity/manager/user_manager.py

fix: fix null bug

---

src/spaceone/identity/error/error_domain.py
src/spaceone/identity/manager/domain_manager.py

fix: add exception case when plugin is not set

---

src/spaceone/identity/manager/authorization_manager.py
src/spaceone/identity/service/authorization_service.py

feat: add request option for authorization

---

src/spaceone/identity/conf/provider_conf.py

feat: add openstack provider

---

src/spaceone/identity/model/policy_model.py

refactor: add unique index to policy name

---

src/spaceone/identity/info/role_info.py
src/spaceone/identity/model/role_model.py

refactor: change role's minimal fields

---

src/spaceone/identity/conf/provider_conf.py

refactor: change openstack provider info

---

src/spaceone/identity/model/policy_model.py

fix: fix unique index issue

---

src/spaceone/identity/manager/user_manager.py

feat: reset actions when updating password

---

src/spaceone/identity/service/token_service.py

fix: fix refresh timeout bug
